/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.jooq.tables.SbDocTb;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbDocTbRecord extends UpdatableRecordImpl<SbDocTbRecord> implements Record3<UInteger, Byte, UInteger> {

    private static final long serialVersionUID = 2060547985;

    /**
     * Setter for <code>sb_db.sb_doc_tb.doc_no</code>. 문서 번호, 시퀀스(=sb_seq-tb) 테이블의 '시퀀스 식별자'(=sq_id)  3번을 참조하며  1부터 시작
     */
    public void setDocNo(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_tb.doc_no</code>. 문서 번호, 시퀀스(=sb_seq-tb) 테이블의 '시퀀스 식별자'(=sq_id)  3번을 참조하며  1부터 시작
     */
    public UInteger getDocNo() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_doc_tb.doc_state</code>. 문서 상태
     */
    public void setDocState(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_tb.doc_state</code>. 문서 상태
     */
    public Byte getDocState() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_doc_tb.last_doc-sq</code>. 마지막 문서 시퀀스 번호, 1부터 시작.
     */
    public void setLastDocSq(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_tb.last_doc-sq</code>. 마지막 문서 시퀀스 번호, 1부터 시작.
     */
    public UInteger getLastDocSq() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, Byte, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, Byte, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return SbDocTb.SB_DOC_TB.DOC_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return SbDocTb.SB_DOC_TB.DOC_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return SbDocTb.SB_DOC_TB.LAST_DOC_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getDocNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getDocState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getLastDocSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDocNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getDocState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getLastDocSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocTbRecord value1(UInteger value) {
        setDocNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocTbRecord value2(Byte value) {
        setDocState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocTbRecord value3(UInteger value) {
        setLastDocSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocTbRecord values(UInteger value1, Byte value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbDocTbRecord
     */
    public SbDocTbRecord() {
        super(SbDocTb.SB_DOC_TB);
    }

    /**
     * Create a detached, initialised SbDocTbRecord
     */
    public SbDocTbRecord(UInteger docNo, Byte docState, UInteger lastDocSq) {
        super(SbDocTb.SB_DOC_TB);

        set(0, docNo);
        set(1, docState);
        set(2, lastDocSq);
    }
}
