/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import kr.pe.codda.jooq.tables.SbDocHistoryTb;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbDocHistoryTbRecord extends UpdatableRecordImpl<SbDocHistoryTbRecord> implements Record6<UInteger, UInteger, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1983644819;

    /**
     * Setter for <code>sb_db.sb_doc_history_tb.doc_no</code>. 문서 번호
     */
    public void setDocNo(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_history_tb.doc_no</code>. 문서 번호
     */
    public UInteger getDocNo() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_doc_history_tb.doc_sq</code>. 문서 시퀀스 번호
     */
    public void setDocSq(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_history_tb.doc_sq</code>. 문서 시퀀스 번호
     */
    public UInteger getDocSq() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_doc_history_tb.file_name</code>. 문서 파일 이름
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_history_tb.file_name</code>. 문서 파일 이름
     */
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_doc_history_tb.subject</code>.
     */
    public void setSubject(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_history_tb.subject</code>.
     */
    public String getSubject() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_doc_history_tb.contents</code>. 문서 내용
     */
    public void setContents(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_history_tb.contents</code>. 문서 내용
     */
    public String getContents() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sb_db.sb_doc_history_tb.reg_dt</code>. 최초 작성일
     */
    public void setRegDt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>sb_db.sb_doc_history_tb.reg_dt</code>. 최초 작성일
     */
    public Timestamp getRegDt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return SbDocHistoryTb.SB_DOC_HISTORY_TB.DOC_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbDocHistoryTb.SB_DOC_HISTORY_TB.DOC_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SbDocHistoryTb.SB_DOC_HISTORY_TB.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbDocHistoryTb.SB_DOC_HISTORY_TB.SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SbDocHistoryTb.SB_DOC_HISTORY_TB.CONTENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return SbDocHistoryTb.SB_DOC_HISTORY_TB.REG_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getDocNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getDocSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDocNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDocSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocHistoryTbRecord value1(UInteger value) {
        setDocNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocHistoryTbRecord value2(UInteger value) {
        setDocSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocHistoryTbRecord value3(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocHistoryTbRecord value4(String value) {
        setSubject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocHistoryTbRecord value5(String value) {
        setContents(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocHistoryTbRecord value6(Timestamp value) {
        setRegDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbDocHistoryTbRecord values(UInteger value1, UInteger value2, String value3, String value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbDocHistoryTbRecord
     */
    public SbDocHistoryTbRecord() {
        super(SbDocHistoryTb.SB_DOC_HISTORY_TB);
    }

    /**
     * Create a detached, initialised SbDocHistoryTbRecord
     */
    public SbDocHistoryTbRecord(UInteger docNo, UInteger docSq, String fileName, String subject, String contents, Timestamp regDt) {
        super(SbDocHistoryTb.SB_DOC_HISTORY_TB);

        set(0, docNo);
        set(1, docSq);
        set(2, fileName);
        set(3, subject);
        set(4, contents);
        set(5, regDt);
    }
}
