/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.jooq.tables.SbUploadImageTb;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbUploadImageTbRecord extends UpdatableRecordImpl<SbUploadImageTbRecord> implements Record4<String, UInteger, String, Long> {

    private static final long serialVersionUID = 250611786;

    /**
     * Setter for <code>sb_db.sb_upload_image_tb.yyyymmdd</code>. 년월일
     */
    public void setYyyymmdd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_upload_image_tb.yyyymmdd</code>. 년월일
     */
    public String getYyyymmdd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_upload_image_tb.day_sq</code>. 일별 순서
     */
    public void setDaySq(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_upload_image_tb.day_sq</code>. 일별 순서
     */
    public UInteger getDaySq() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_upload_image_tb.fname</code>. 이미지 파일 이름
     */
    public void setFname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_upload_image_tb.fname</code>. 이미지 파일 이름
     */
    public String getFname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_upload_image_tb.fsize</code>. 이미지 파일 크기
     */
    public void setFsize(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_upload_image_tb.fsize</code>. 이미지 파일 크기
     */
    public Long getFsize() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, UInteger, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, UInteger, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SbUploadImageTb.SB_UPLOAD_IMAGE_TB.YYYYMMDD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbUploadImageTb.SB_UPLOAD_IMAGE_TB.DAY_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SbUploadImageTb.SB_UPLOAD_IMAGE_TB.FNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return SbUploadImageTb.SB_UPLOAD_IMAGE_TB.FSIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getYyyymmdd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getDaySq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getFsize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getYyyymmdd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDaySq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getFsize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUploadImageTbRecord value1(String value) {
        setYyyymmdd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUploadImageTbRecord value2(UInteger value) {
        setDaySq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUploadImageTbRecord value3(String value) {
        setFname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUploadImageTbRecord value4(Long value) {
        setFsize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUploadImageTbRecord values(String value1, UInteger value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbUploadImageTbRecord
     */
    public SbUploadImageTbRecord() {
        super(SbUploadImageTb.SB_UPLOAD_IMAGE_TB);
    }

    /**
     * Create a detached, initialised SbUploadImageTbRecord
     */
    public SbUploadImageTbRecord(String yyyymmdd, UInteger daySq, String fname, Long fsize) {
        super(SbUploadImageTb.SB_UPLOAD_IMAGE_TB);

        set(0, yyyymmdd);
        set(1, daySq);
        set(2, fname);
        set(3, fsize);
    }
}
